#pragma once

#include <string>
#include <vector>
#include <map>
#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <libpq-fe.h>
#include "fuzzy_index.hpp"
#include "tfidf_vectorizer.hpp"
#include "encode.hpp"
#include "utils.hpp"

using namespace std;

#define MAX_NGRAMS 500000

namespace PopularNgram {

inline void generate_ngram_histogram(PGconn* conn, const string& table_name, const string& column_name, const string& output_file) {
    // Query to get ALL names from the specified table
    lb_log("Querying %s names from PostgreSQL...", table_name.c_str());
    string query_str = "SELECT DISTINCT " + column_name + " FROM musicbrainz." + table_name + " WHERE " + column_name + " IS NOT NULL ORDER BY " + column_name;
    PGresult *res = PQexec(conn, query_str.c_str());
    
    if (PQresultStatus(res) != PGRES_TUPLES_OK) {
        lb_error("Query failed: %s", PQerrorMessage(conn));
        PQclear(res);
        throw std::runtime_error("PostgreSQL query failed");
    }
    
    // Create vectorizer and tokenize dynamically as we fetch rows
    lb_log("Tokenizing into 3-grams...");
    TfIdfVectorizer vectorizer(false, true, false);
    EncodeSearchData encode;
    
    map<string, int> ngram_counts;
    int num_rows = PQntuples(res);
    
    for (int i = 0; i < num_rows; i++) {
        char* name = PQgetvalue(res, i, 0);
        if (name && strlen(name) > 0) {
            string item_name(name);
            string encoded_name = encode.encode_string(item_name);
            vector<string> tokens = vectorizer.tokenise_document(encoded_name);
            
            // Count each 3-gram
            for (const auto& token : tokens) {
                ngram_counts[token]++;
            }
        }
        
        if ((i + 1) % 1000000 == 0) {
            lb_log("Processed %d %s names...", i + 1, table_name.c_str());
        }
    }
    
    int count = num_rows;
    PQclear(res);
    
    lb_log("Total %s names processed: %d", table_name.c_str(), count);
    
    // Sort by frequency (ascending)
    vector<pair<string, int>> sorted_ngrams(ngram_counts.begin(), ngram_counts.end());
    sort(sorted_ngrams.begin(), sorted_ngrams.end(),
         [](const pair<string, int>& a, const pair<string, int>& b) {
             return a.second < b.second;
         });
    lb_log("Total sorted unique 3-grams: %zu", ngram_counts.size());
    
    // Write UTF-8 encoded 3-grams to file
    FILE* fp = fopen(output_file.c_str(), "w");
    if (!fp) {
        lb_error("Error: Failed to open file for writing: %s", output_file.c_str());
        throw std::runtime_error("Failed to open output file");
    }
    
    fprintf(fp, "# popular ngrams -- generated by make_mapping --popular-ngrams");
    fprintf(fp, "# { \"total_rows\": %d }\n", count);
    int total = 0;
    for (const auto& pair : sorted_ngrams) {
        fprintf(fp, "%s\n", pair.first.c_str());
        total++;
        if (total == MAX_NGRAMS)
            break;
    }
    
    fclose(fp);
    lb_log("Successfully wrote %zu unique 3-grams to: %s", ngram_counts.size(), output_file.c_str());
}

inline void generate_popular_ngrams() {
    try {
        lb_log("Generating 3-gram histograms from release and recording names...");
        
        // Get DB connection string from environment variable
        const char* db_connect = std::getenv("CANONICAL_MUSICBRAINZ_DATA_CONNECT");
        if (!db_connect || strlen(db_connect) == 0) {
            throw std::runtime_error("CANONICAL_MUSICBRAINZ_DATA_CONNECT environment variable not set");
        }
        
        lb_log("Connecting to PostgreSQL...");
        
        // Connect to PostgreSQL using libpq
        PGconn *conn = PQconnectdb(db_connect);
        
        if (PQstatus(conn) != CONNECTION_OK) {
            lb_error("Connection to database failed: %s", PQerrorMessage(conn));
            PQfinish(conn);
            throw std::runtime_error("PostgreSQL connection failed");
        }
        
        // Generate histogram for release names
        lb_log("\n=== Processing Release Names ===");
        generate_ngram_histogram(conn, "release", "name", "./release_ngrams.txt");
        
        // Generate histogram for recording names
        lb_log("\n=== Processing Recording Names ===");
        generate_ngram_histogram(conn, "recording", "name", "./recording_ngrams.txt");
        
        PQfinish(conn);
        
    } catch (const std::exception& e) {
        lb_error("Error generating 3-gram histogram: %s", e.what());
        throw;
    }
}

inline vector<string> load_ngrams(const string& filename) {
    vector<string> ngrams;
    
    FILE* fp = fopen(filename.c_str(), "r");
    if (!fp) {
        lb_error("Error: Failed to open file for reading: %s", filename.c_str());
        throw std::runtime_error("Failed to open ngram file");
    }
    
    char buffer[256];
    while (fgets(buffer, sizeof(buffer), fp)) {
        // Remove newline
        size_t len = strlen(buffer);
        if (len > 0 && buffer[len - 1] == '\n') {
            buffer[len - 1] = '\0';
        }
        
        // Only add non-empty 3-character strings
        string ngram(buffer);
        if (ngram.length() == 3) {
            ngrams.push_back(ngram);
        }
    }
    
    fclose(fp);
    lb_log("Loaded %zu n-grams from: %s", ngrams.size(), filename.c_str());
    return ngrams;
}

} // namespace PopularNgram
